<a href="https://colab.research.google.com/github/Xiaolingz0663/TensorFlow-Study/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we 're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we are going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulate tensors
* Tensors & NumPy
* Using @tf.function ( a way to speed up your regular Python functions)
* Using GPUs with tensorFlow
* Exercises

### **Notion Note**

https://www.notion.so/Intro-Deep-Learning-with-TensorFlow-ee517b06c7264c7891bef502cf4546a7

#Colab Shotcut: 
1. command+ MM | turn the cell to markdown
2. command + shift + space | search on calab

##**14. Create Unchangeable Tensor with `tf.constant`**


* Scalar : a single number
* Vector : a number with direction (e.g. Wind Speed and Direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers ( 0-dim -> Scalar, 1-dim -> Vector)

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
# tf.constant creates a constant tensor from a tensor-like object
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check num of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [6]:
#create a matrix (matrix has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what is the number dimensions of another_matrix?
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

## **15. Creating Changeable Tensor with `tf.Variable`**

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# change one ofthe elements in the changeable_tensor
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
changeable_tensor[0]=7

TypeError: ignored

In [ ]:
# .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# try change the unchangeable tensor
unchangeable_tensor[0]

In [ ]:
unchangeable_tensor[0]=7

In [ ]:
unchangeable_tensor[0].assign(7)

## **16. Create Random Tensor with `tf.random.uniform`, `tf.random.normal`**

Random tensors are tnesors of some abitrary size which contain random numbers

- tf.random.uniform 
  Outputs random values from a uniform distribution.

- tf.random.normal
  Outputs random values from a normal distribution.




In [ ]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3,2))
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

In [ ]:
random_1 == random_2

True. Because the seeds are the same

## **17. Shuffle Elements Order of Tensors `tf.random.shuffle`**

In [ ]:
# shuffle a tensure (valuable for when you want to shuffle your data so the inherent order doesn't effect learning )
not_shuffled = tf. constant([[10,7],
                             [3,4],
                             [2,5]])
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
# shuffle out non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled)

Evey time you run there are different order, unless you add seeds.
Random Seeds are derived from two seeds:
1. Golbal seeds
2. Operation-level seeds

In [ ]:
#Set Operation-level seed
tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
#Set Global seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

### The interations with operation-level seeds is as follows:
1. if neither global seed nor the operation seed is set, we get different results for every call to the random op and every re-run of the program.
2. if the global seed is set but operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run.


In [ ]:
# 'tf.function' acts like a re-run of a program
tf.random.set_seed(123)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a,b
  
@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1]) 
  return a,b

print(f())
print(g())

In [ ]:
tf.random.set_seed(40)
a=tf.random.uniform([2])
b=tf.random.uniform([2])
print(a, b)

In [ ]:
tf.random.set_seed(40)
c=tf.random.uniform([2])
d=tf.random.uniform([2])
print(c, d)

3. If the operation seed is set, we get different results for every call to the random op, but the same sequence for every re-run of the program

In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

* if you want to the shuffuled tensors to be in the same order, we got to use the global level and operation level seeds.

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

##**18. Other Way to Made Tensors**: `tf.ones`, `tf.zeros`, `tf.constant(numpy_array)`

In [ ]:
#create a tensor of all ones
tf.ones([10,5])

In [ ]:
#create a tensor of all zeros
tf.zeros(shape=(3,4))

### turn NumPy arrays into tensor: `tf.constant(numpy_array, shape=())`
The main difference between NumPy arrays and TensorFlow tensors is that ensors can be cun on a GPU

In [ ]:
 #trun NumPy into tensors
 import numpy as np
 numpy_A= np.arange(1,25,dtype=np.int32)
 numpy_A

 #X = tf.constant(some_matrix)
 #y = tf.constant(vector)

In [ ]:

A = tf.constant(numpy_A)
A

In [ ]:
# change the shape of a numpy array has to be the equal elements as the array. e.g. 2*3*4= 24
B = tf.constant(numpy_A, shape=(2,3,4))
B

## **19. Tensors Attributes**
- shape
- Rank: the number of tensor dimensions
- Axis or dimension
- Size

In [ ]:
 #Create a rank 4 tensor (4 dimensions)
 rank_4_tensor = tf.zeros(shape=[2,3,4,5])
 rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
# get various attributes of tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions/Rank:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

## **20.Indexing and Expanding Tensors**
Tensors can be indexed just like Python lists


In [ ]:
list = [2,3,4,5]
list[:2]

In [ ]:
rank_4_tensor

In [ ]:
#get the first 2 elements of each dimension
rank_4_tensor[:2,:3,:3,:2]

In [ ]:
#get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

In [ ]:
rank_4_tensor[:,:1,:1,:1]

In [ ]:
# create a rank 2 tensor 
rank_2_tensor=tf.constant([[10,7],
                          [3,4]])
rank_2_tensor.ndim

In [ ]:
#get the last item of each of rank_2_tensor
rank_2_tensor[:,-1]

### Add dimension

In [ ]:
rank_2_tensor

#### `tf.newaxis`

In [ ]:
#Insert a dimension at the end of rank_2_tensor
rank_3_tensor1 = rank_2_tensor[...,tf.newaxis] # ... means all previous axis 
# or rank_3_tensor = rank_2_ tensor[:,:,tf.newaxis]
# same as rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

The shape of rank_2_tensor is (2,2); after adding a dimension, shape is (2,2,1)

In [ ]:
#Inset a dimen at the second axis
rank_3_tensor2 = rank_2_tensor[:,tf.newaxis,:]
rank_3_tensor2

#### `tf.expand_dims`

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis= -1) 
# "-1" means expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) 
# expand the 0-axis as the first axis

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)
#expand the 1-axis which would be the second axis

## **21. Manipulating Tensors with Basic Operations**

In [ ]:
#add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

In [ ]:
# Orignal tensor is unchanged
tensor

In [ ]:
#Multiplication
tensor * 10

In [ ]:
#Substraction
tensor - 10

In [ ]:
# tensorflow built-in function
tf.multiply(tensor,10)

## **22. Matrix Mulitiplication  `tf.linalg.matmul` / `tf.matmul`**

linalg => linaege algebra

Two rules of matrix mutplication:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

E.g. TensorA = shape(4,3), TensorB=shape(3,2)
Inner dimen of TensorA is 3, which matches the Inner dimen of TensorB
the resulting matrix is (4,2)

In [ ]:
# matrix multiplication in tensorlfow
tensor

In [ ]:
tf.matmul(tensor,tensor)

In [ ]:
# use operation
tensor * tensor

In [ ]:
tensor_test1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_test2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(tensor_test1,tensor_test2)

In [ ]:
tensor_test1 * tensor_test2

In [ ]:
# matrix mutliplication with Python operator "@"
tensor_test1 @ tensor_test2

In [ ]:

# try matrix multiply tensors of same shape
# it doesn't work because the inner dimen is not matched
tensor_test2 @ tensor_test2

In [ ]:
tf.matmul(tensor_test2,tensor_test2)

In [ ]:
tf.matmul(tf.ones([4,2]),tf.ones([2,3]))

In [ ]:
# difference between transpose and reshape
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.transpose(X)
Z = tf.reshape(X,shape=(2,3))

X,Y,Z

#### **The Dot Product**

Matrix multiplication is also referred to as the dot product.

you can perform matrix multiplication using:

* `tf.matmul()`

* `tf.tensordot()`

* @

In [ ]:
# Perform the dot product on X and Y (requires X and Y are transposed)
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

tf.tensordot(tf.transpose(X),Y,axes=1)

In [ ]:
tf.matmul(tf.transpose(X),Y)

In [ ]:
tf.tensordot()

In [ ]:
# perform matrxi multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

In [ ]:
#Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

In [ ]:
# check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped (2, 3):")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed:")
print(tf.transpose(Y))

Generally, when performaing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

## **25. Change Tensor Datatype**
The reason of chaning dtype is that a 16 bit floating point types can run faste and use less memory

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

In [ ]:
C = tf.constant([7,10])
C.dtype

In [ ]:
# Change float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D

In [ ]:
# change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

## **26.Aggregating Tensors**

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
import numpy as np

In [ ]:
# get the absolute values
D = tf.constant([-7,-10])
D

In [ ]:
# get the absolute values
tf.abs(D)

In [ ]:
E= tf.constant(np.random.randint(0,100,size=50))
E

In [ ]:
# get the minimum
Min = tf.math.reduce_min(E)
Min

In [ ]:
#get the maximum
Max = tf.math.reduce_max(E)
Max

In [ ]:
# get the mean
Mean = tf.cast(tf.math.reduce_mean(E),dtype=tf.float32)
Mean

In [ ]:
# get the sum
Sum = tf.math.reduce_sum(E)
Sum

In [ ]:
import tensorflow_probability as tfp

In [ ]:
VAR = tfp.stats.variance(E)
VAR

In [ ]:
# for math method, dtype needs to be float
VAR2 = tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))
VAR2

In [ ]:
STD = tf.math.reduce_std(tf.cast(E,dtype=tf.float32))
STD

### Find the postional maximum and minimum

In [ ]:
# create a new tensor for finding positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

In [ ]:
# find the positional maximum
tf.argmax(F)

In [ ]:
# Index on out largest value postion
F[tf.argmax(F)]

In [ ]:
#FInd the max value of F
tf.reduce_max(F)

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# find postional minimum
tf.argmin(F)

In [ ]:
# find min value
F[tf.argmin(F)]

## 29. Squeezing a Tensor ( removing all single dimensions / size 1)

In [16]:
# create a tensor 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [17]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [18]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## **30. One-Hot Encoding Tensors** / Dummy values

In [20]:
# Create a lits tof indices
some_list = [0,1,2,3]

# One hot encode out list of inidces
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [21]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4, on_value="2",off_value="3")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'2', b'3', b'3', b'3'],
       [b'3', b'2', b'3', b'3'],
       [b'3', b'3', b'2', b'3'],
       [b'3', b'3', b'3', b'2']], dtype=object)>

## **31.Othe Math functions**
Suqaring,log,square root

In [22]:
# Create tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [23]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [27]:
# square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [30]:
# log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## **32.Tensors and Numpy**

TensorFlow interacts beautifully with NumPy arrays.

Note: one of the differents betweeb tf and np is that tf tensor can be run on a GPU or TPU for faster numerical processing.

In [32]:
import numpy as np

In [34]:
# Create tensor directly from a numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [35]:
# convert tensor backto numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [36]:
# Convert tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [37]:
# the default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# check the dtypes
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

numpy create float 63 type, and tensor create float 32 type.

## **32. Finding Access to GPUs**

In [39]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

Right now we use CPU to process, but GPU/TCU is much faster

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

There is a option to choose GPU.

In [2]:
# chose GPU
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
# check what type of GPU you use
!nvidia-smi

Fri Jul 30 17:45:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 Note: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.