<a href="https://colab.research.google.com/github/Xiaolingz0663/TensorFlow-Study/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we 're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we are going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulate tensors
* Tensors & NumPy
* Using @tf.function ( a way to speed up your regular Python functions)
* Using GPUs with tensorFlow
* Exercises

### **Notion Note**

https://www.notion.so/Intro-Deep-Learning-with-TensorFlow-ee517b06c7264c7891bef502cf4546a7

#Colab Shotcut: 
1. command+ MM | turn the cell to markdown
2. command + shift + space | search on calab

##**Create Tensor with `tf.constant`**


* Scalar : a single number
* Vector : a nuber with direction (e.g. Wind Speed and Direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers ( 0-dim -> Scalar, 1-dim -> Vector)

In [11]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [12]:
# Create tensors with tf.constant()
# tf.constant creates a constant tensor from a tensor-like object
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [13]:
# check num of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [14]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [15]:
# check the dimension of our vector
vector.ndim

1

In [16]:
#create a matrix (matrix has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [18]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
# what is the number dimensions of another_matrix?
another_matrix.ndim

2

In [22]:
# create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

## **Creating Tensor with `tf.Variable`**

In [24]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [25]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# change one ofthe elements in the changeable_tensor
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [27]:
changeable_tensor[0]=7

TypeError: ignored

In [28]:
# .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [29]:
# try change the unchangeable tensor
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [30]:
unchangeable_tensor[0]=7

TypeError: ignored

In [31]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored