<a href="https://colab.research.google.com/github/Xiaolingz0663/TensorFlow-Study/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we 're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we are going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulate tensors
* Tensors & NumPy
* Using @tf.function ( a way to speed up your regular Python functions)
* Using GPUs with tensorFlow
* Exercises

### **Notion Note**

https://www.notion.so/Intro-Deep-Learning-with-TensorFlow-ee517b06c7264c7891bef502cf4546a7

#Colab Shotcut: 
1. command+ MM | turn the cell to markdown
2. command + shift + space | search on calab

##**Create Unchangeable Tensor with `tf.constant`**


* Scalar : a single number
* Vector : a nuber with direction (e.g. Wind Speed and Direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers ( 0-dim -> Scalar, 1-dim -> Vector)

In [2]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
# Create tensors with tf.constant()
# tf.constant creates a constant tensor from a tensor-like object
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check num of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of our vector
vector.ndim

1

In [7]:
#create a matrix (matrix has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# what is the number dimensions of another_matrix?
another_matrix.ndim

2

In [11]:
# create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

## **Creating Changeable Tensor with `tf.Variable`**

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# change one ofthe elements in the changeable_tensor
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [16]:
changeable_tensor[0]=7

TypeError: ignored

In [17]:
# .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# try change the unchangeable tensor
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [19]:
unchangeable_tensor[0]=7

TypeError: ignored

In [20]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

## **Create Random Tensor with `tf.random.uniform`, `tf.random.normal`**

Random tensors are tnesors of some abitrary size which contain random numbers

- tf.random.uniform 
  Outputs random values from a uniform distribution.

- tf.random.normal
  Outputs random values from a normal distribution.




In [21]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

True. Because the seeds are the same

## **Shuffle Elements Order of Tensors `tf.random.shuffle`**

In [24]:
# shuffle a tensure (valuable for when you want to shuffle your data so the inherent order doesn't effect learning )
not_shuffled = tf. constant([[10,7],
                             [3,4],
                             [2,5]])
not_shuffled.ndim

2

In [25]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [26]:
# shuffle out non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [27]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

Evey time you run there are different order, unless you add seeds.
Random Seeds are derived from two seeds:
1. Golbal seeds
2. Operation-level seeds

In [28]:
#Set Operation-level seed
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [29]:
#Set Global seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### The interations with operation-level seeds is as follows:
1. if neither global seed nor the operation seed is set, we get different results for every call to the random op and every re-run of the program.
2. if the global seed is set but operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run.


In [33]:
# 'tf.function' acts like a re-run of a program
tf.random.set_seed(123)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a,b
  
@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1]) 
  return a,b

print(f())
print(g())

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2772479], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2772479], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)


3. If the operation seed is set, we get different results for every call to the random op, but the same sequence for every re-run of the program

In [38]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04026103], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04026103], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2772479], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.97267234], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04026103], dtype=float32)>)


In [35]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.255216], shape=(1,), dtype=float32)
tf.Tensor([0.31072247], shape=(1,), dtype=float32)
