<a href="https://colab.research.google.com/github/Xiaolingz0663/TensorFlow-Study/blob/main/TensorFlowExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [6]:
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [7]:
vector = tf.constant([0,1])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>, 1)

In [8]:
matrix = tf.constant([[1,2],[3,4]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, 2)

In [9]:
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[7,8]],
                      [[9,10],[11,12]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]]], dtype=int32)>, 3)

2.Find the shape, rank and size of the tensors you created in 1.

In [11]:
tensor.shape, tensor.ndim,tf.size(tensor)

(TensorShape([3, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [12]:
A = tf.random.Generator.from_seed(42)
A = A.normal(shape=(5,300))
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
        -1.0722276 , -0.00586287],
       [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
         1.155565  , -0.10707551],
       [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
         1.216793  , -1.24293   ],
       [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
        -0.73970354,  0.0177109 ],
       [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
         0.5656089 ,  0.18439196]], dtype=float32)>

In [13]:
B = tf.random.Generator.from_seed(32)
B = B.normal(shape=(5,300))
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ,  0.4356279 , ...,  0.54241335,
        -0.25226593,  0.43689874],
       [-1.5446119 , -0.9279166 ,  1.5999255 , ..., -0.448121  ,
         0.3995735 , -2.1588635 ],
       [-0.16122076, -1.040813  ,  0.44564843, ...,  1.5315233 ,
         0.51527184, -0.76588607],
       [ 1.6272374 ,  0.04138071, -0.10412996, ...,  2.6236527 ,
        -1.2969457 ,  0.09658346],
       [-0.5660935 , -0.25495797,  0.93636596, ...,  0.23323336,
        -0.04431101, -0.31474254]], dtype=float32)>

4, Multiply the two tensors you created in 3 using matrix multiplication.


In [16]:
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 26.850746  ,  -7.4877777 ,  24.129826  ,   7.994731  ,
        -17.440565  ],
       [ -5.832143  ,   9.289821  ,  -6.7012367 ,  24.065567  ,
        -12.137888  ],
       [ -4.800009  ,   0.04769087,  -4.496765  , -26.365547  ,
         11.644641  ],
       [  5.2373424 ,  33.045654  , -22.157877  ,  -6.7776356 ,
        -43.803703  ],
       [-15.45096   ,  -3.8501692 ,  38.412575  ,  10.450214  ,
          0.73112726]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.


In [18]:
tf.tensordot(A,tf.transpose(B),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 26.850746  ,  -7.4877777 ,  24.129826  ,   7.994731  ,
        -17.440565  ],
       [ -5.832143  ,   9.289821  ,  -6.7012367 ,  24.065567  ,
        -12.137888  ],
       [ -4.800009  ,   0.04769087,  -4.496765  , -26.365547  ,
         11.644641  ],
       [  5.2373424 ,  33.045654  , -22.157877  ,  -6.7776356 ,
        -43.803703  ],
       [-15.45096   ,  -3.8501692 ,  38.412575  ,  10.450214  ,
          0.73112726]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [19]:
C = tf.random.uniform(shape=(224,224,3))
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7973887 , 0.77467525, 0.10477257],
        [0.36442268, 0.32663298, 0.92103887],
        [0.3099017 , 0.54893005, 0.20876908],
        ...,
        [0.57267475, 0.20365167, 0.8341985 ],
        [0.6471853 , 0.39962673, 0.7184979 ],
        [0.17047489, 0.1801095 , 0.36858094]],

       [[0.3313626 , 0.20500588, 0.9590621 ],
        [0.16653657, 0.583161  , 0.3789072 ],
        [0.64866066, 0.75223196, 0.23265016],
        ...,
        [0.9096906 , 0.5571407 , 0.15819132],
        [0.05612552, 0.49548542, 0.42162013],
        [0.4767877 , 0.15280461, 0.85334086]],

       [[0.655094  , 0.83468306, 0.8666209 ],
        [0.7955097 , 0.5585139 , 0.5120914 ],
        [0.02901924, 0.10903811, 0.6249144 ],
        ...,
        [0.1867944 , 0.21356308, 0.19002569],
        [0.62358284, 0.0115881 , 0.23292518],
        [0.3820045 , 0.95863175, 0.7558192 ]],

       ...,

       [[0.18771982, 0.66226876, 0.14155626],
        [0.00

8. Find the min and max values of the tensor you created in 6 along the first axis.


In [23]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7418137e-06>

In [21]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [27]:
D = tf.random.normal(shape=(1,224,224,3))
F = tf.squeeze(D)
F.shape

TensorShape([224, 224, 3])

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [30]:
G = tf.constant([1,2,3,2,4,5,6,7,8,0,10])
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

10. One-hot encode the tensor you created in 9

In [31]:
tf.one_hot(G,depth=10)

<tf.Tensor: shape=(11, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>